package api

import (
	"log/slog"
	"net/http"
)

func NewServer(logger *slog.Logger, handler *Handler) http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /healthz", handler.HandleHealth)
	mux.HandleFunc("GET /v1/whoami", handler.HandleSession)
	mux.HandleFunc("GET /v1/agent-adapters", handler.HandleAgentAdapters)
	mux.HandleFunc("POST /v1/agent-adapters/{id}/probe", handler.HandleAgentAdapterProbe)
	mux.HandleFunc("POST /v1/agent-adapters/{id}/refresh-launcher", handler.HandleAgentAdapterRefreshLauncher)
	mux.HandleFunc("GET /v1/agent-adapters/{id}/health", handler.HandleAgentAdapterHealth)
	mux.HandleFunc("GET /v1/agent-chat/sessions", handler.HandleAgentChatSessions)
	mux.HandleFunc("POST /v1/agent-chat/sessions", handler.HandleCreateAgentChatSession)
	mux.HandleFunc("GET /v1/agent-chat/sessions/{id}", handler.HandleAgentChatSession)
	mux.HandleFunc("DELETE /v1/agent-chat/sessions/{id}", handler.HandleDeleteAgentChatSession)
	mux.HandleFunc("GET /v1/agent-chat/sessions/{id}/stream", handler.HandleAgentChatSessionStream)
	mux.HandleFunc("POST /v1/agent-chat/sessions/{id}/cancel", handler.HandleCancelAgentChatSession)
	mux.HandleFunc("POST /v1/agent-chat/sessions/{id}/close", handler.HandleCloseAgentChatSession)
	mux.HandleFunc("POST /v1/agent-chat/sessions/{id}/messages", handler.HandleCreateAgentChatMessage)
	mux.HandleFunc("GET /v1/agent-chat/sessions/{id}/messages/{message_id}/files", handler.HandleAgentChatMessageFiles)
	mux.HandleFunc("GET /v1/agent-chat/sessions/{id}/messages/{message_id}/files/{path...}", handler.HandleAgentChatMessageFileDiff)
	mux.HandleFunc("POST /v1/agent-chat/sessions/{id}/messages/{message_id}/revert", handler.HandleRevertAgentChatMessageFiles)
	mux.HandleFunc("GET /v1/agent-chat/sessions/{id}/approvals", handler.HandleListAgentChatApprovals)
	mux.HandleFunc("GET /v1/agent-chat/sessions/{id}/approvals/{approval_id}", handler.HandleGetAgentChatApproval)
	mux.HandleFunc("POST /v1/agent-chat/sessions/{id}/approvals/{approval_id}/resolve", handler.HandleResolveAgentChatApproval)
	mux.HandleFunc("POST /v1/agent-chat/sessions/{id}/approvals/{approval_id}/cancel", handler.HandleCancelAgentChatApproval)
	mux.HandleFunc("GET /v1/agent-chat/grants", handler.HandleListAgentChatGrants)
	mux.HandleFunc("DELETE /v1/agent-chat/grants/{grant_id}", handler.HandleDeleteAgentChatGrant)
	mux.HandleFunc("POST /v1/workspace-dialog", handler.HandleWorkspaceDialog)
	mux.HandleFunc("GET /v1/provider-presets", handler.HandleProviderPresets)
	mux.HandleFunc("GET /v1/tasks", handler.HandleTasks)
	mux.HandleFunc("POST /v1/tasks", handler.HandleCreateTask)
	mux.HandleFunc("GET /v1/tasks/{id}", handler.HandleTask)
	mux.HandleFunc("DELETE /v1/tasks/{id}", handler.HandleDeleteTask)
	mux.HandleFunc("POST /v1/tasks/{id}/start", handler.HandleStartTask)
	mux.HandleFunc("GET /v1/tasks/{id}/approvals", handler.HandleTaskApprovals)
	mux.HandleFunc("GET /v1/tasks/{id}/approvals/{approval_id}", handler.HandleTaskApproval)
	mux.HandleFunc("POST /v1/tasks/{id}/approvals/{approval_id}/resolve", handler.HandleResolveTaskApproval)
	mux.HandleFunc("GET /v1/tasks/{id}/runs", handler.HandleTaskRuns)
	mux.HandleFunc("GET /v1/tasks/{id}/runs/{run_id}", handler.HandleTaskRun)
	mux.HandleFunc("GET /v1/tasks/{id}/runs/{run_id}/stream", handler.HandleTaskRunStream)
	mux.HandleFunc("GET /v1/tasks/{id}/runs/{run_id}/events", handler.HandleTaskRunEvents)
	mux.HandleFunc("POST /v1/tasks/{id}/runs/{run_id}/events", handler.HandleAppendTaskRunEvent)
	mux.HandleFunc("POST /v1/tasks/{id}/runs/{run_id}/retry", handler.HandleRetryTaskRun)
	mux.HandleFunc("POST /v1/tasks/{id}/runs/{run_id}/retry-from-turn", handler.HandleRetryTaskRunFromTurn)
	mux.HandleFunc("POST /v1/tasks/{id}/runs/{run_id}/resume", handler.HandleResumeTaskRun)
	mux.HandleFunc("POST /v1/tasks/{id}/runs/{run_id}/continue", handler.HandleContinueTaskRun)
	mux.HandleFunc("POST /v1/tasks/{id}/runs/{run_id}/cancel", handler.HandleCancelTaskRun)
	mux.HandleFunc("GET /v1/tasks/{id}/runs/{run_id}/steps", handler.HandleTaskRunSteps)
	mux.HandleFunc("GET /v1/tasks/{id}/runs/{run_id}/steps/{step_id}", handler.HandleTaskRunStep)
	mux.HandleFunc("POST /v1/tasks/{id}/runs/{run_id}/patches/{artifact_id}/revert", handler.HandleRevertTaskRunPatch)
	mux.HandleFunc("POST /v1/tasks/{id}/runs/{run_id}/patches/{artifact_id}/apply", handler.HandleApplyTaskRunPatch)
	mux.HandleFunc("GET /v1/tasks/{id}/runs/{run_id}/patches/{artifact_id}", handler.HandleTaskRunPatch)
	mux.HandleFunc("GET /v1/tasks/{id}/runs/{run_id}/patches", handler.HandleTaskRunPatches)
	mux.HandleFunc("GET /v1/tasks/{id}/runs/{run_id}/artifacts/{artifact_id}", handler.HandleTaskRunArtifact)
	mux.HandleFunc("GET /v1/tasks/{id}/runs/{run_id}/artifacts", handler.HandleTaskRunArtifacts)
	mux.HandleFunc("GET /v1/tasks/{id}/artifacts", handler.HandleTaskArtifacts)
	mux.HandleFunc("GET /v1/events", handler.HandleEvents)
	mux.HandleFunc("GET /v1/events/stream", handler.HandleEventsStream)
	mux.HandleFunc("GET /v1/chat/sessions", handler.HandleChatSessions)
	mux.HandleFunc("POST /v1/chat/sessions", handler.HandleCreateChatSession)
	mux.HandleFunc("GET /v1/chat/sessions/{id}", handler.HandleChatSession)
	mux.HandleFunc("PATCH /v1/chat/sessions/{id}", handler.HandleUpdateChatSession)
	mux.HandleFunc("DELETE /v1/chat/sessions/{id}", handler.HandleDeleteChatSession)
	mux.HandleFunc("GET /admin/traces", handler.HandleTraces)
	mux.HandleFunc("GET /v1/traces", handler.HandleTracesOrTrace)
	mux.HandleFunc("GET /admin/retention/runs", handler.HandleRetentionRuns)
	mux.HandleFunc("POST /admin/retention/run", handler.HandleRetentionRun)
	mux.HandleFunc("GET /admin/budget", handler.HandleBudgetStatus)
	mux.HandleFunc("GET /admin/accounts/summary", handler.HandleAccountSummary)
	mux.HandleFunc("GET /admin/requests", handler.HandleRequestLedger)
	mux.HandleFunc("POST /admin/budget/topup", handler.HandleBudgetTopUp)
	mux.HandleFunc("POST /admin/budget/limit", handler.HandleBudgetSetLimit)
	mux.HandleFunc("POST /admin/budget/reset", handler.HandleBudgetReset)
	mux.HandleFunc("GET /admin/control-plane", handler.HandleControlPlaneStatus)
	mux.HandleFunc("GET /admin/control-plane/providers/local-discovery", handler.HandleLocalProviderDiscovery)
	mux.HandleFunc("POST /admin/control-plane/providers", handler.HandleControlPlaneCreateProvider)
	mux.HandleFunc("PATCH /admin/control-plane/providers/{id}", handler.HandleControlPlaneUpdateProvider)
	mux.HandleFunc("DELETE /admin/control-plane/providers/{id}", handler.HandleControlPlaneDeleteProvider)
	mux.HandleFunc("PUT /admin/control-plane/providers/{id}/api-key", handler.HandleControlPlaneSetProviderAPIKey)
	mux.HandleFunc("POST /admin/control-plane/policy-rules", handler.HandleControlPlaneUpsertPolicyRule)
	mux.HandleFunc("POST /admin/control-plane/policy-rules/delete", handler.HandleControlPlaneDeletePolicyRule)
	mux.HandleFunc("POST /admin/control-plane/pricebook", handler.HandleControlPlaneUpsertPricebookEntry)
	mux.HandleFunc("POST /admin/control-plane/pricebook/delete", handler.HandleControlPlaneDeletePricebookEntry)
	mux.HandleFunc("POST /admin/control-plane/pricebook/import/preview", handler.HandleControlPlanePricebookImportPreview)
	mux.HandleFunc("POST /admin/control-plane/pricebook/import/apply", handler.HandleControlPlanePricebookImportApply)
	mux.HandleFunc("GET /admin/providers", handler.HandleProviderStatus)
	mux.HandleFunc("GET /admin/providers/history", handler.HandleProviderHealthHistory)
	mux.HandleFunc("GET /admin/runtime/stats", handler.HandleRuntimeStats)
	mux.HandleFunc("GET /admin/mcp/cache", handler.HandleMCPCacheStats)
	mux.HandleFunc("POST /v1/mcp/probe", handler.HandleMCPProbe)
	mux.HandleFunc("GET /v1/models", handler.HandleModels)
	mux.HandleFunc("PUT /v1/model-capabilities/overrides", handler.HandleUpsertModelCapabilityOverride)
	mux.HandleFunc("DELETE /v1/model-capabilities/overrides", handler.HandleDeleteModelCapabilityOverride)
	mux.HandleFunc("POST /v1/model-capabilities/probes", handler.HandleRecordModelCapabilityProbe)
	mux.HandleFunc("POST /v1/chat/completions", handler.HandleChatCompletions)
	mux.HandleFunc("POST /v1/messages", handler.HandleMessages)

	// Embedded UI catch-all. Go 1.22+ mux selects the most specific pattern
	// first, so `GET /v1/...` etc. continue to route to their handlers above.
	// Non-API paths fall through here and are served from ui/dist (or the
	// fallback page when the UI bundle isn't embedded).
	mux.Handle("GET /", staticUIHandler())

	return Chain(
		mux,
		TraceContextMiddleware,
		RequestIDMiddleware,
		SameOriginMiddleware,
		LoggingMiddleware(logger),
		RecoveryMiddleware(logger),
	)
}
