import type { RuntimeConsoleViewModel } from "../app/useRuntimeConsole";

export function createRuntimeConsoleFixture(
  overrides: Partial<RuntimeConsoleViewModel["state"]> = {},
): RuntimeConsoleViewModel["state"] {
  return {
    usageSummary: null,
    activeChatSession: null,
    activeChatSessionID: "",
    agentAdapterID: "codex",
    agentAdapters: [],
    chatCancelling: false,
    chatSessions: [],
    hecateRTKEnabled: false,
    hecateRTKAvailable: false,
    hecateRTKPath: "",
    newChatAgentID: "hecate",
    agentWorkspace: "",
    agentWorkspaceBranch: "",
    chatError: "",
    chatErrorAction: "",
    chatErrorCode: "",
    chatErrorRequestID: "",
    chatErrorStatus: null,
    chatErrorTraceID: "",
    chatLoading: false,
    streamingContent: null,
    chatResult: null,
    chatTarget: "agent",
    pendingToolCalls: [],
    queuedChatMessages: [],
    cloudModels: [],
    cloudProviders: [],
    settingsConfig: null,
    settingsError: "",
    copiedCommand: "",
    error: "",
    health: { status: "ok", time: "2026-04-21T10:00:00Z" },
    healthyCloudProviders: 0,
    healthyLocalProviders: 0,
    healthyProviders: 0,
    loading: false,
    localModels: [],
    localProviderIssues: [],
    localProviders: [],
    message: "Say hello",
    systemPrompt: "",
    model: "gpt-4o-mini",
    modelFilter: "all",
    models: [],
    notice: null,
    session: { label: "Local" },
    providerFilter: "auto",
    providerPresets: [],
    providerScopedModels: [],
    providers: [],
    usageEvents: [],
    retentionError: "",
    retentionLastRun: null,
    retentionLoading: false,
    retentionRuns: [],
    retentionSubsystems: "",
    runtimeHeaders: null,
    visibleModels: [],
    pendingApprovalsBySessionID: new Map(),
    chatGrants: [],
    chatGrantsLoading: false,
    chatGrantsError: "",
    agentAdapterApprovalMode: "",
    agentAdapterHealthByID: new Map(),
    agentAdapterHealthLoadingByID: new Map(),
    ...overrides,
  };
}

export function createRuntimeConsoleActions(): RuntimeConsoleViewModel["actions"] {
  return {
    copyCommand: async () => undefined,
    cancelAgentChat: async () => undefined,
    chooseAgentWorkspace: async () => true,
    createChatSession: async () => undefined,
    deleteChatSession: async () => undefined,
    deletePolicyRule: async () => undefined,
    loadDashboard: async () => undefined,
    loadRetentionRuns: async () => undefined,
    renameChatSession: async () => undefined,
    setAgentAdapterID: () => undefined,
    setNewChatAgent: () => undefined,
    setAgentWorkspace: () => undefined,
    setChatTarget: () => undefined,
    setMessage: () => undefined,
    removeQueuedChatMessage: () => undefined,
    updateQueuedChatMessage: () => undefined,
    setSystemPrompt: () => undefined,
    setModel: () => undefined,
    setModelFilter: () => undefined,
    setProviderFilter: () => undefined,
    refreshProviders: async () => undefined,
    setRetentionSubsystems: () => undefined,
    submitChat: async () => undefined,
    submitToolResults: async () => undefined,
    runRetention: async () => undefined,
    selectChatSession: async () => undefined,
    startNewChat: () => undefined,
    upsertPolicyRule: async () => undefined,
    updateToolResult: () => undefined,
    setProviderAPIKey: async () => undefined,
    createProvider: async () => undefined,
    deleteProvider: async () => undefined,
    setProviderBaseURL: async () => undefined,
    setProviderName: async () => undefined,
    setProviderCustomName: async () => undefined,
    upsertModelCapabilityOverride: async () => true,
    recordModelCapabilityProbe: async () => true,
    deleteModelCapabilityOverride: async () => true,
    getChatApproval: async () => null,
    listChatMessageFiles: async () => [],
    getChatMessageFileDiff: async () => null,
    revertChatMessageFiles: async () => true,
    resolveTaskApproval: async () => true,
    resolveChatApproval: async () => true,
    cancelChatApproval: async () => true,
    listChatGrants: async () => undefined,
    deleteChatGrant: async () => true,
    setChatConfigOption: async () => true,
    setHecateRTKEnabled: async () => true,
    probeAgentAdapter: async () => null,
    setAgentAdapterCredential: async () => true,
    deleteAgentAdapterCredential: async () => true,
    dismissNotice: () => undefined,
  };
}
