import type { RuntimeConsoleViewModel } from "../app/useRuntimeConsole";

export function createRuntimeConsoleFixture(
  overrides: Partial<RuntimeConsoleViewModel["state"]> = {},
): RuntimeConsoleViewModel["state"] {
  return {
    accountSummary: null,
    budget: null,
    budgetActionError: "",
    budgetAmountUsd: "1.00",
    budgetLimitUsd: "5.00",
    activeAgentChatSession: null,
    activeAgentChatSessionID: "",
    activeChatSession: null,
    activeChatSessionID: "",
    agentAdapterID: "codex",
    agentAdapters: [],
    agentChatCancelling: false,
    agentChatSessions: [],
    agentWorkspace: "",
    agentWorkspaceBranch: "",
    chatError: "",
    chatErrorAction: "",
    chatErrorCode: "",
    chatErrorRequestID: "",
    chatErrorStatus: null,
    chatErrorTraceID: "",
    chatLoading: false,
    streamingContent: null,
    chatResult: null,
    chatTarget: "agent",
    pendingToolCalls: [],
    queuedChatMessages: [],
    chatSessions: [],
    cloudModels: [],
    cloudProviders: [],
    settingsConfig: null,
    settingsError: "",
    copiedCommand: "",
    error: "",
    health: { status: "ok", time: "2026-04-21T10:00:00Z" },
    healthyCloudProviders: 0,
    healthyLocalProviders: 0,
    healthyProviders: 0,
    loading: false,
    localModels: [],
    localProviderIssues: [],
    localProviders: [],
    message: "Say hello",
    systemPrompt: "",
    model: "gpt-4o-mini",
    modelFilter: "all",
    models: [],
    notice: null,
    session: { label: "Local" },
    providerFilter: "auto",
    providerPresets: [],
    providerScopedModels: [],
    providers: [],
    requestLedger: [],
    retentionError: "",
    retentionLastRun: null,
    retentionLoading: false,
    retentionRuns: [],
    retentionSubsystems: "",
    runtimeHeaders: null,
    chatSessionsHasMore: false,
    chatSessionsLoadingMore: false,
    visibleModels: [],
    pendingApprovalsBySessionID: new Map(),
    agentChatGrants: [],
    agentChatGrantsLoading: false,
    agentChatGrantsError: "",
    agentAdapterApprovalMode: "",
    agentAdapterHealthByID: new Map(),
    agentAdapterHealthLoadingByID: new Map(),
    ...overrides,
  };
}

export function createRuntimeConsoleActions(): RuntimeConsoleViewModel["actions"] {
  return {
    copyCommand: async () => undefined,
    cancelAgentChat: async () => undefined,
    chooseAgentWorkspace: async () => true,
    createChatSession: () => undefined,
    deleteChatSession: async () => undefined,
    deletePolicyRule: async () => undefined,
    loadDashboard: async () => undefined,
    resetBudget: async () => undefined,
    renameChatSession: async () => undefined,
    setBudgetAmountUsd: () => undefined,
    setBudgetLimitUsd: () => undefined,
    setAgentAdapterID: () => undefined,
    setAgentWorkspace: () => undefined,
    setChatTarget: () => undefined,
    setMessage: () => undefined,
    removeQueuedChatMessage: () => undefined,
    updateQueuedChatMessage: () => undefined,
    setSystemPrompt: () => undefined,
    setModel: () => undefined,
    setModelFilter: () => undefined,
    setProviderFilter: () => undefined,
    refreshProviders: async () => undefined,
    setRetentionSubsystems: () => undefined,
    setBudgetLimit: async () => undefined,
    submitChat: async () => undefined,
    submitToolResults: async () => undefined,
    runRetention: async () => undefined,
    loadMoreChatSessions: async () => undefined,
    selectChatSession: async () => undefined,
    startNewChat: () => undefined,
    topUpBudget: async () => undefined,
    upsertPolicyRule: async () => undefined,
    updateToolResult: () => undefined,
    setProviderAPIKey: async () => undefined,
    createProvider: async () => undefined,
    deleteProvider: async () => undefined,
    setProviderBaseURL: async () => undefined,
    setProviderName: async () => undefined,
    setProviderCustomName: async () => undefined,
    upsertModelCapabilityOverride: async () => true,
    recordModelCapabilityProbe: async () => true,
    deleteModelCapabilityOverride: async () => true,
    upsertPricebookEntry: async () => undefined,
    deletePricebookEntry: async () => undefined,
    previewPricebookImport: async () => ({ fetched_at: "", unchanged: 0 }),
    applyPricebookImport: async () => ({ fetched_at: "", unchanged: 0 }),
    getAgentChatApproval: async () => null,
    listAgentChatMessageFiles: async () => [],
    getAgentChatMessageFileDiff: async () => null,
    revertAgentChatMessageFiles: async () => true,
    resolveTaskApproval: async () => true,
    resolveAgentChatApproval: async () => true,
    cancelAgentChatApproval: async () => true,
    listAgentChatGrants: async () => undefined,
    deleteAgentChatGrant: async () => true,
    probeAgentAdapter: async () => null,
    setAgentAdapterCredential: async () => true,
    deleteAgentAdapterCredential: async () => true,
    dismissNotice: () => undefined,
  };
}
